name: Continuous Integration Laravel 6
on:
  push:
    branches:
    - master

jobs:

  deploy:
    runs-on: ubuntu-latest 

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mercator        
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'
            extensions: zip, curl, mbstring, dom, soap, xdebug, mysql, gd

      - name: Install dependencies
        run: |
            composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env

      - name: Migrate database
        run: |
          php artisan migrate

      - name: Insert test data
        run: |
          mysql mercator < mercator_data.sql

      - name: Generate Application Key
        run: |
          php artisan key:generate
          php artisan passport:keys

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk
        env:
          APP_ENV: local
          APP_URL: "http://127.0.0.1:8000"
          DB_CONNECTION: mysql
          DB_DATABASE: dusk
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root