name: PHP Insights

on: 
  push:
    branches: 
      - master

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'
          extensions: zip, curl, mbstring, dom, soap, xdebug, mysql, gd

    - name: Install dependencies
      run: |
          composer update --prefer-stable --prefer-dist --no-interaction 

    - name: Publish the configuration
      run: |
          php artisan vendor:publish --all

    - uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
      with:
        args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80

