name: PHP Insights

on: push

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: MilesChou/composer-action@master
      with:
        args: update -q --no-ansi --no-interaction --prefer-stable --prefer-dist --no-interaction --no-suggest

    - uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
      with:
        args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80

