name: PHP Insights

on: push

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
        run: |
            composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

    - uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
      with:
        args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80

